jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.6
      - run: |
          haxe -version
          haxelib install --always build-cpp.hxml
          haxe build-cpp.hxml
